### ISSUE TITLE
Set up Travis build

### ISSUE THREAD

**Issue by remojansen** [AtSpy/AtSpy#10]

**Comment by remojansen** [comment]
Hi guys, the build is ready. It is failing because there is an issue with the Linux version of PhantomJS (used by travis). But as soon as that package gets updated our build will be working.

We need to follow this to fix the build https://github.com/ariya/phantomjs/issues/12948

I'm using OSX and everything is fine locally. For now when you do some changes run `gulp watch` and the build will be executed every time some changes are saved.

**Comment by jj09** [comment]
Hey,

Looks like there is an issue with phantomjs2 on Windows as well. When I do npm install I get:

`Unexpected platform or architecture: win32 ia32`

I didn't investigate. Will wait for stable build (hopefully soon?).

**Comment by remojansen** [comment]
Hi,

If you want to be able to run it in your machine you can manually do the following (I'm just guessing that this will work):

1. Download the PhantomJS  2.0 windows binary file from http://phantomjs.org/download.html
2. Comment [line 45 in package.json](https://github.com/AtSpy/AtSpy/blob/master/package.json#L45)
3. Run `npm install`
4. Let Karma know where is the PhantomJS binary file located in your machine by changing [line 13 in karma.conf.js](https://github.com/AtSpy/AtSpy/blob/master/karma.conf.js#L13)

That should work locally but we need to wait for the Linux issue to be solved for the Travis build to work.
